# Generated by Django 3.2.9 on 2022-06-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220614_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='fecha_de_muerte',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
    ]
