# Generated by Django 3.2.9 on 2022-06-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='resumen',
            field=models.TextField(help_text='Coloca aqui un resumen de la pelicula', max_length=400, null=True),
        ),
    ]
