# Generated by Django 3.2.9 on 2022-06-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220613_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['primer_apellido']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['titulo']},
        ),
    ]
