# Generated by Django 3.2.9 on 2022-06-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_director_fecha_de_muerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='primer_apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='director',
            name='primer_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='anio',
            field=models.CharField(help_text='Coloca aquí el año de la pelicula', max_length=4, verbose_name='Año'),
        ),
    ]
